name: Run tests and upload coverage

on:
  pull_request:
  push:
    branches:
      - develop
      - devnet
      - main
      - avkr003/cc

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -coverprofile=coverage.txt ./...

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true

      - name: Check keeper package coverage
        run: |
          modules=$(find . -type d -name "x" -not -path "*/vendor/*")
          for module in $modules; do
            keeper_coverage=$(go tool cover -func=coverage.txt | grep "${module}/keeper" | awk '{print $3}' | sed 's/%//')
            if (( $(echo "$keeper_coverage < 90" | bc -l) )); then
              echo "Coverage for ${module}/keeper is below 90%: ${keeper_coverage}%"
              exit 1
            fi
          done
